node_name "ci-ubuntu"
#cookbook_path ["/tmp/kitchen/cookbooks", "/tmp/kitchen/site-cookbooks"]
#data_bag_path "/tmp/kitchen/data_bags"
#environment_path "/tmp/kitchen/environments"
#node_path "/tmp/kitchen/nodes"
#role_path "/tmp/kitchen/roles"
#client_path "/tmp/kitchen/clients"
#user_path "/tmp/users"
validation_key "/tmp/validation.pem"
client_key "/tmp/client.pem"
chef_server_url "http://127.0.0.1:8889"